title: "Muhammad Bilal Saad"
description: "Web Developer & University Student from Pakistan"
baseurl: ""
url: "https://bilalsaad.github.io"

author:
  name: Muhammad Bilal Saad
  email: bilalsaad@email.com

github_username: Muhammad-BilalSaad

header_pages:
  - about.md
  - projects.md
  - contact.md

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

show_excerpts: true
